baseURL = ""
languageCode = "en-us"
title = "Passion(s) Unraveled"
theme = "minimal"
# disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Passion(s) Unraveled podcast"
    description = "Your next favourite podcast!"
    # githubUsername = "#"
    accent = "#FF928B"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = false # no syntax highlighting

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Episodes"
    weight = 3

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:me@example.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://podcasts.apple.com/"
    name = "podcast"
    weight = 2

[[menu.icon]]
    url = "https://open.spotify.com/show/"
    name = "spotify"
    weight = 3

[[menu.icon]]
    url = "#"
    name = "rss"
    weight = 4
